
services:
  web-check:
    image: ghcr.io/vnt87/web-check:latest
    ports:
      - "6666:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
